name = "shortstories-app"
compatibility_date = "2024-01-01"

[env.production]
name = "shortstories-app"
route = "shortstories.app/*"

# KV namespace bindings for data storage
[[env.production.kv_namespaces]]
binding = "STORIES_KV"
id = "your-kv-namespace-id"  # Replace with actual KV namespace ID
preview_id = "your-preview-kv-namespace-id"  # Replace with preview KV namespace ID

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"
DOMAIN = "shortstories.app"

# Build configuration
[build]
command = "npm run build"
publish = "public"

# Functions configuration
[functions]
directory = "functions"

# Pages configuration
[pages]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Custom domains
[[pages.custom_domains]]
domain = "shortstories.app"

[[pages.custom_domains]]
domain = "www.shortstories.app"