name = "shortstories-app"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

# KV namespace bindings for data storage
[[kv_namespaces]]
binding = "STORIES_KV"
id = "284bfacfe9684f47a49bdfa21d1940a3"
preview_id = "5d293dde943d4ab9baf9169ed3d91fae"

# Environment variables
[vars]
ENVIRONMENT = "production"
DOMAIN = "shortstories.app"